name: vertica_test_project
version: 0.0.1
config-version: 2

profile: vertica_test_project

source-paths: ["models"]
data-paths: ["data", "seeds"]
test-paths: ["tests"]
docs-paths: ["docs"]
target-path: "target"
log-path: "dbt_logs"

clean-targets: ["compiled", "dbt_logs", "dbt_modules"]

require-dbt-version: ">=0.18.0"

models:
  test_model:
    materialized: table
  staging:
    materialized: view
    tags: ["staging"]
  marts:
    materialized: table
    tags: ["marts"]

seeds:
  test_model:
    +database: test_db
    +enabled: true


   
